### ISSUE TITLE
client field first parameter: `({ data, variables })` instead of `data`

### ISSUE THREAD

**Issue by rbalicki2** [isographlabs/isograph#116]
* Right now, we don't give you the ability to read the fragment variables. What a bummer! That seems useful.
* Another advantage of this is that passing an object here allows us to, in the future, pass additional props as part of that first parameter. `refetch` might be useful, for example.
* This is a great first issue, it exposes you to both the compiler and the runtime

## Gist

- Modify `EagerReaderArtifact` and `ComponentReaderArtifact`'s types (but not `RefetchReaderArtifact`)
- Wherever we call `.resolver(data, ...)`, we should instead pass `{ data, variables }`. (Except when we call `field.refetchReaderArtifact.resolver(...)` in `read.ts`)
- Modify https://github.com/isographlabs/isograph/blob/d57417f09b33df676192f7176f4f465c99567c41/crates/graphql_artifact_generation/src/iso_overload_file.rs#L82-L95 to reflect the new parameter
- Rebuild the demos (`pnpm run build-demos`)
- Spot check to ensure stuff works

**Comment by ch1ffa** [comment]
@rbalicki2 assign please to me
