### ISSUE TITLE
break up handle_compile_command

### ISSUE THREAD

**Issue by rbalicki2** [isographlabs/isograph#174]
Let's chat about this before you start, I want to make sure we're on the same page.

`handle_compile_command` should be broken up as follows:

- there should be a `create_validated_schema_from_sources` function that accepts the parsed isograph literals, and the parsed graphql schema and extensions (specifically, the "Outcome" object)
- the parsed isograph literals and parsed schema and extensions should be data structures that are wrapped in newtypes, and which contain a `new` method that returns a `Result<Self, BatchCompileError>`. This `new` method should **not** take an `&mut IsographSchema`!!!!
    - the parsed isograph literals struct should probably be `struct ParsedIsographLiterals(HashMap<FilePath, HashSet<ParsedIsographLiterals>>)`. This is because we're going to modify this data structure on a per-file basis in #175 .
- `handle_compile_command` should create these data structures and pass them to the `create_validated_schema_from_sources`, and that validated schema should be used to create and write the artifacts.

**Comment by rbalicki2** [comment]
cc @ch1ffa

**Comment by ch1ffa** [comment]
@rbalicki2 I'll take it after #58
