### ISSUE TITLE
Use broken up handle_compile_command parts to make watch mode more efficient

### ISSUE THREAD

**Issue by rbalicki2** [isographlabs/isograph#175]
After #174, we can modify watch mode as follows:

- don't just recompile everything
- instead, create the data structures **and clone them**, and then pass the cloned versions to `create_validated_schema_from_sources` and so on.
- when we get an event that a path has changed, determine whether the changed paths includes any schema files, in which case, re-parse the schema. Likewise, if a path in the components directory changed, recreate the hashmap of parsed isograph literals.
- pass this to `create_validated_schema_from_sources` and generate artifacts

----

- note: instead of re-creating the hashmap of parsed isograph literals if a single isograph literal changes, instead, we can just mutate the hash map of parsed isograph literals! That can be done as part of this, or as a follow up

**Comment by rbalicki2** [comment]
cc @ch1ffa

**Comment by ch1ffa** [comment]
@rbalicki2 assign please
