### ISSUE TITLE
Migrate off of cargo-watch

### ISSUE THREAD

**Issue by rbalicki2** [isographlabs/isograph#195]
https://github.com/watchexec/cargo-watch?tab=readme-ov-file#maintenance

We should use `watch-exec` directly, or `bacon`, or find some other solution.

**Comment by lanesawyer** [comment]
I might be able to give this a go with `bacon` soon! I was reading up on the deprecation and on `bacon` the other day.

**Comment by rbalicki2** [comment]
Amazing!! 🙌🙌🙌
