### ISSUE TITLE
Bug: extra final "argument" is ignored instead of erroring

### ISSUE THREAD

**Issue by rbalicki2** [isographlabs/isograph#99]
```
export const AdItemDisplayWrapper = iso(`
  field AdItem.AdItemDisplayWrapper @component {
    AdItemDisplay @loadable(lazyLoadArtifact: true, whatIsThisWhyIsThisAllowedItShouldNotBeNoooo)
    AlsoWorks @loadable(lazyLoadArtifact: true, finalColon:)
  }
`)(fn)
```

is valid. It shouldn't be! We should emit an error.

Something is wrong in https://github.com/isographlabs/isograph/blob/75a6eaf1ab694fd51d571394c24c132050191e59/crates/isograph_lang_parser/src/parse_iso_literal.rs#L389, and on line https://github.com/isographlabs/isograph/blob/75a6eaf1ab694fd51d571394c24c132050191e59/crates/isograph_lang_parser/src/parse_iso_literal.rs#L264

`parse_argument` successfully parses `whatIsThisWhyIsThisAllowedItShouldNotBeNoooo` (which advances the `PeekableLexer` past it). Then, it errors out on the next token (the closing paren.) This does not advance the `PeekableLexer` past the closing paren. So, when we return to https://github.com/isographlabs/isograph/blob/75a6eaf1ab694fd51d571394c24c132050191e59/crates/isograph_lang_parser/src/parse_iso_literal.rs#L402, the next token is the paren and we continue.

Anyway, I have a variety of ideas for what to do here:

- give `PeekableLexer` a way to speculatively parse (i.e. parse but don't advance the tape). This may be hard! The lexer isn't cloneable, and that presumably requires that.
- (I think this is the correct approach) teach `parse_delimited_list` about the closing paren, and have it only return `Ok` if it ever encounters a closing paren. It should always unwrap `parse_item(...)?` (i.e. use the `?` operator), i.e. it should error out if it fails to parse any item.
      - as an added bonus, we can and should add support for empty lists!

We probably have this bug in the GraphQL side, too!

**Comment by PatrykWalach** [comment]
This was done in #140
